-- MySQL Script generated by MySQL Workbench
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema OnlineSales
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `OnlineSales` ;

-- -----------------------------------------------------
-- Schema OnlineSales
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OnlineSales` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `OnlineSales` ;

-- -----------------------------------------------------
-- Table `OnlineSales`.`Products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OnlineSales`.`Products` ;

CREATE TABLE IF NOT EXISTS `OnlineSales`.`Products` (
  `ProductId` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NOT NULL,
  `Description` VARCHAR(255) NULL,
  `Price` DOUBLE NOT NULL,
  `Quantity` INT NOT NULL,
  `Category` VARCHAR(50) NULL,
  `OtherInfo` LONGTEXT NULL,
  `MadeIn` VARCHAR(100) NULL,
  `Seller` VARCHAR(100) NULL,
  `ISBN` INT NULL,
  `OutOfProduction` TINYINT(1) NOT NULL DEFAULT 0,
  `Tags` VARCHAR(250) NULL DEFAULT 'New',
  `StorageLocation` VARCHAR(45) NULL DEFAULT 'Storage 1',
  PRIMARY KEY (`ProductId`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
